In [1]:
import tensorflow as tf

In [12]:
colors_list=[(0,0,0), (255,0,0), (255,255,0)]

In [31]:
def dice_coef(y_true, y_pred):
    intersection = tf.reduce_sum(y_true*y_pred)
    return (2. * intersection + 1.)/(tf.reduce_sum(y_true)+tf.reduce_sum(y_pred)+1)

### Image 1

### Overall

In [29]:
y_true = tf.io.read_file('Valid_Mask/7105b8ee8d4c00c513b334fdfdcd6c49_mask.png')
y_true = tf.image.decode_png(y_true, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_true,color), axis=-1)
    one_hot_map.append(class_map)
#one_hot_map = one_hot_map[2]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_true = tf.cast(one_hot_map, tf.float32)

In [30]:
y_pred = tf.io.read_file('Val_Results_reconstructed_exp4/7105b8ee8d4c00c513b334fdfdcd6c49.png')
y_pred = tf.image.decode_png(y_pred, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_pred,color), axis=-1)
    one_hot_map.append(class_map)
#one_hot_map = one_hot_map[2]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_pred = tf.cast(one_hot_map, tf.float32)

In [32]:
dice_coef(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9673307>

### Black

In [33]:
y_true = tf.io.read_file('Valid_Mask/7105b8ee8d4c00c513b334fdfdcd6c49_mask.png')
y_true = tf.image.decode_png(y_true, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_true,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[0]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_true = tf.cast(one_hot_map, tf.float32)

In [34]:
y_pred = tf.io.read_file('Val_Results_reconstructed_exp4/7105b8ee8d4c00c513b334fdfdcd6c49.png')
y_pred = tf.image.decode_png(y_pred, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_pred,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[0]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_pred = tf.cast(one_hot_map, tf.float32)

In [35]:
dice_coef(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.98761225>

### Red

In [36]:
y_true = tf.io.read_file('Valid_Mask/7105b8ee8d4c00c513b334fdfdcd6c49_mask.png')
y_true = tf.image.decode_png(y_true, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_true,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[1]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_true = tf.cast(one_hot_map, tf.float32)

In [37]:
y_pred = tf.io.read_file('Val_Results_reconstructed_exp4/7105b8ee8d4c00c513b334fdfdcd6c49.png')
y_pred = tf.image.decode_png(y_pred, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_pred,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[1]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_pred = tf.cast(one_hot_map, tf.float32)

In [38]:
dice_coef(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.8207178>

### Yellow

In [39]:
y_true = tf.io.read_file('Valid_Mask/7105b8ee8d4c00c513b334fdfdcd6c49_mask.png')
y_true = tf.image.decode_png(y_true, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_true,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[2]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_true = tf.cast(one_hot_map, tf.float32)

In [40]:
y_pred = tf.io.read_file('Val_Results_reconstructed_exp4/7105b8ee8d4c00c513b334fdfdcd6c49.png')
y_pred = tf.image.decode_png(y_pred, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_pred,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[2]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_pred = tf.cast(one_hot_map, tf.float32)

In [41]:
dice_coef(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.90391994>

### Image 2

### Overall

In [42]:
y_true = tf.io.read_file('Valid_Mask/d0cf594c5106fb84e894c0b12013f367_mask.png')
y_true = tf.image.decode_png(y_true, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_true,color), axis=-1)
    one_hot_map.append(class_map)
#one_hot_map = one_hot_map[2]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_true = tf.cast(one_hot_map, tf.float32)

In [45]:
y_pred = tf.io.read_file('Val_Results_reconstructed_exp5/d0cf594c5106fb84e894c0b12013f367.png')
y_pred = tf.image.decode_png(y_pred, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_pred,color), axis=-1)
    one_hot_map.append(class_map)
#one_hot_map = one_hot_map[2]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_pred = tf.cast(one_hot_map, tf.float32)

In [46]:
dice_coef(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9404538>

### Black

In [47]:
y_true = tf.io.read_file('Valid_Mask/d0cf594c5106fb84e894c0b12013f367_mask.png')
y_true = tf.image.decode_png(y_true, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_true,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[0]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_true = tf.cast(one_hot_map, tf.float32)

In [48]:
y_pred = tf.io.read_file('Val_Results_reconstructed_exp5/d0cf594c5106fb84e894c0b12013f367.png')
y_pred = tf.image.decode_png(y_pred, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_pred,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[0]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_pred = tf.cast(one_hot_map, tf.float32)

In [49]:
dice_coef(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.96817684>

### Red

In [50]:
y_true = tf.io.read_file('Valid_Mask/d0cf594c5106fb84e894c0b12013f367_mask.png')
y_true = tf.image.decode_png(y_true, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_true,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[1]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_true = tf.cast(one_hot_map, tf.float32)

In [51]:
y_pred = tf.io.read_file('Val_Results_reconstructed_exp5/d0cf594c5106fb84e894c0b12013f367.png')
y_pred = tf.image.decode_png(y_pred, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_pred,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[1]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_pred = tf.cast(one_hot_map, tf.float32)

In [52]:
dice_coef(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.93551767>

### Yellow

In [53]:
y_true = tf.io.read_file('Valid_Mask/d0cf594c5106fb84e894c0b12013f367_mask.png')
y_true = tf.image.decode_png(y_true, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_true,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[2]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_true = tf.cast(one_hot_map, tf.float32)

In [54]:
y_pred = tf.io.read_file('Val_Results_reconstructed_exp5/d0cf594c5106fb84e894c0b12013f367.png')
y_pred = tf.image.decode_png(y_pred, channels=3)
one_hot_map = []
for color in colors_list:
    class_map = tf.reduce_all(tf.equal(y_pred,color), axis=-1)
    one_hot_map.append(class_map)
one_hot_map = one_hot_map[2]
one_hot_map = tf.stack(one_hot_map, axis=-1)
y_pred = tf.cast(one_hot_map, tf.float32)

In [55]:
dice_coef(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.87183976>